services:
  app:
    container_name: "uglyapp-be"
    build:
      context: ../..
      dockerfile: apps/uglyapp-be/Dockerfile
    ports:
      - '3128:3000'
    depends_on:
      - mysql
      - redis
    environment:
      MYSQL_HOST: mysql
      REDIS_HOST: redis
      PRIVATE_KEY_PATH: keys/ed25519_private.pem
      PUBLIC_KEY_PATH: keys/ed25519_public.pem
      ADDRESS: 0.0.0.0
    volumes:
      - ./secrets/certs:/app/keys:ro
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: uglyapp
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - '3306:3306'
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
